---
spring:
  profiles: default
server:
  port: 8010
eureka:
  instance:
    hostname: eureka
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/

---
spring:
  profiles: primary
  application:
    name: eureka-server-secondary
server:
  port: 8011
eureka:
  instance:
    hostname: eureka-secondary
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
