---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lol/lol
          searchPaths: ConfigData
        # "native" is used when the native profile is active, for local tests with a classpath repo:
        native:
          searchLocations: classpath:offline-repository/
  profiles:
    active: native
server:
  port: 8001